@URL=http://127.0.0.1:5000

GET {{URL}}/api/v1/user HTTP/1.1

###
DELETE  {{URL}}/api/v1/user/65361c40b1b6e56324358cf9 HTTP/1.1
###
GET {{URL}}/api/v1/user/65361824240c9a0841e7760b HTTP/1.1
###
POST {{URL}}/api/v1/user
Content-Type: application/json

{
    # "firstName":"Eric",
    # "lastName":"Han",
    # "email":"eric@gmail.com",
    # "password":"test1322!@"
}
###
PATCH {{URL}}/api/v1/user/65361c45b1b6e56324358cfa
Content-Type: application/json

{
    "firstName":"Eric Updated"
}